env: "local"
http_server:
  address: "localhost:8085"
  timout: 4s
  idle_timeout: 30s
  user: "user"
  password: "password"
storage:
  user: "app"
  password: "secret"
  database: "geomatrix"
  host: "localhost"
  port: 54325
